name: "terraform_aws_destroy"

on:
  workflow_dispatch:


jobs:
  terraform_destroy:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_USER_AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_USER_AWS_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
